name: Run Experiments

on:
  push:
    branches:
      - main  # Adjust this to your branch

jobs:
  run_experiments:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python benchmark/benchmark-graph-similarity-search.py

    - name: Upload results to server
      uses: actions/upload-artifact@v2
      with:
        name: results
        path: benchmark/results/GraphSimilaritySearch/last-results.csv
